apiVersion: extensions/v1
kind: Deployment
metadata:
  name: rnd-angular
  labels:
    name: rnd-angular
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: rnd-angular
    spec:
      containers:
      - name: rnd-angular
        image: rnd-angular:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rnd-angular
  labels:
    name: rnd-angular
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: rnd-angular